name: Publish Allure Report

on:
  workflow_run:
    workflows: [ "Magento Hybrid Automation CI" ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Allure HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-html-report
          path: ./allure-report

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Allure Report to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
